export enum Property {
  Id = 'id',
  Title = 'title',
  Desc = 'desc',
  Type = 'type',
  CreatedAt = 'createdAt',
  Photo = 'photo',
  Sku = 'sku',
  Strings = 'strings',
  Count = 'count',
  TotalRating = 'totalRating',
  Price = 'price',
  Name = 'name',
  Email = 'email',
  IsAdmin = 'isAdmin',
  Password = 'password',
  PasswordHash  = 'passwordHash',
  Pros = 'pros',
  Cons = 'cons',
  Comment = 'comment',
  Rating = 'rating',
  Port = 'port',
  Reviews = 'reviews',
  ReviewCount = 'reviewCount'
}
